spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:mysql://localhost:${DB_PORT}/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}

firebase:
  credentials:
    path: ${FIREBASE_CREDENTIALS_PATH}
  storageBucket:
    name: ${FIREBASE_STORAGEBUCKET_NAME}

logging:
  level:
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG


