spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/social_media?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret-key: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  access-token-expiration: 600000
  refresh-token-expiration: 604800000

